name             'common'
maintainer       'bageljp'
maintainer_email 'kadoyama.keisuke@gmail.com'
license          'All rights reserved'
description      'Installs/Configures common'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.0.1'
depends          'user'
depends          'sudo'
depends          'yum'
depends          'yum-epel'
